services:
  back:
    build: ./back
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app_network

  front:
    build: ./front
    ports:
      - "8080:80"
    depends_on:
      - back
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
